// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIaLndzxU0LFClIOZfBZDtNSON-pLl72g',
    appId: '1:244854241740:web:58c7d6b2a6eed425ce8569',
    messagingSenderId: '244854241740',
    projectId: 'prakflutterfirebase-edcdf',
    authDomain: 'prakflutterfirebase-edcdf.firebaseapp.com',
    databaseURL: 'https://prakflutterfirebase-edcdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prakflutterfirebase-edcdf.appspot.com',
    measurementId: 'G-4P097X0ZGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-DdGdhZ0l0jZ_mg7mehNC39rAnpk4vUk',
    appId: '1:244854241740:android:d2e7130f7b4a9d89ce8569',
    messagingSenderId: '244854241740',
    projectId: 'prakflutterfirebase-edcdf',
    databaseURL: 'https://prakflutterfirebase-edcdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prakflutterfirebase-edcdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgC1_js1lca5b4aEix_4zZRoRbrGp3QWI',
    appId: '1:244854241740:ios:6f28881154ac1b40ce8569',
    messagingSenderId: '244854241740',
    projectId: 'prakflutterfirebase-edcdf',
    databaseURL: 'https://prakflutterfirebase-edcdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prakflutterfirebase-edcdf.appspot.com',
    iosClientId: '244854241740-h1p5cfpp1qs9mar0t44rml5s4phe4efe.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikum6',
  );
}
